FruitsAndVegetables/ViewModels/ShoppingCartViewModel.cs
using FruitsAndVegetables.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FruitsAndVegetables.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

FruitsAndVegetables/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FruitsAndVegetables.Data.interfaces;
using FruitsAndVegetables.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FruitsAndVegetables.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }
        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some drinks first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }
        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! :) ";
            return View();
        }

    }
}

FruitsAndVegetables/Controllers/ProductController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FruitsAndVegetables.Data.interfaces;
using FruitsAndVegetables.ViewModels;
using Microsoft.AspNetCore.Mvc; //
using FruitsAndVegetables.Data.Models;

namespace FruitsAndVegetables.Controllers
{
    public class ProductController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductRepository _productRepository;
        public ProductController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }
        // public ViewResult List()
        // {

        //     ViewBag.Name = "List Products";
        //     ProductListViewModel vm = new ProductListViewModel();
        //     vm.Products = _productRepository.Products;
        //    vm.CurrentCategory = "FruitsAndVegetablesCategory";
        //    return View(vm);
        //}

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                products = _productRepository.Products.OrderBy(p => p.ProduceId);
                currentCategory = "All Products";
            }
            else
            {
                if (string.Equals("Fruit", _category, StringComparison.OrdinalIgnoreCase))
                   products = _productRepository.Products.Where(p => p.CategoryId.Equals(1)).OrderBy(p => p.Name);
                else
                    products = _productRepository.Products.Where(p => p.CategoryId.Equals(2)).OrderBy(p => p.Name);

                currentCategory = _category;
            }

            return View(new ProductListViewModel
            {
                Products = products,
                CurrentCategory = currentCategory
            });
        }

        
    }
}

FruitsAndVegetables/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FruitsAndVegetables.Data.interfaces;
using FruitsAndVegetables.Data.Models;
using FruitsAndVegetables.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FruitsAndVegetables.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IProductRepository productRepository, ShoppingCart shoppingCart)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var sCVM = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(sCVM);
        }

        public RedirectToActionResult AddToShoppingCart(int produceId)
        {
            var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProduceId == produceId);
            if(selectedProduct!= null){
                _shoppingCart.AddToCart(selectedProduct,1);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int produceId)
        {
            var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProduceId == produceId);
            if (selectedProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }
            return RedirectToAction("Index");
        }
    }
}

FruitsAndVegetables/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the products in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Product</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
            <tr>
                <td class="text-center">@line.Amount</td>
                <td class="text-left">@line.NameProduct</td>
                <td class="text-right">@line.PriceProduct.ToString("c")</td>
          <td class="text-right">
        @((line.Amount * line.PriceProduct).ToString("c"))
        </td>
        <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-produceId="@line.ProduceId"></a></td>
                
            </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
                @*<a class="btn-group">*@
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more products<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Product" asp-action="List" asp-route-category="Fruits">Fruits</a></li>
                    <li><a asp-controller="Product" asp-action="List" asp-route-category="Vegetables">Vegetables</a></li>
                </ul>
                @*</a>*@
</div>
    </div>
</div>